# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: required
cache: packages

# precise fails because unmet deps in libgdal-dev can not be insalled

matrix:
    include:
        - os: linux
          r: release
          dist: trusty
          env: R_CODECOV=true

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

